# Generated by Django 5.2.2 on 2025-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_feedback',
            field=models.JSONField(blank=True, help_text='Structured AI feedback for this resume.', null=True),
        ),
    ]
