# Generated by Django 5.2.2 on 2025-06-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes about this resume', null=True),
        ),
    ]
